### ISSUE TITLE
All Categories show for user

### ISSUE THREAD

**Issue by hindsa-nabeel** [SythilTech/Odoo#35] opened 2018-09-05 14:25 UTC
Hi Steven,
I have created few categories in my Odoo setup, I then created a customer and in the Website Support tab, under Category Name, I picked only a couple of categories. When I logged-in with this created user, I was surprised to see that the user can see all categories!! Also all categories are visible to anyone even before logging-in.

The idea is that I wanted to use Category as a filter. So that for confidentiality reasons you don't want other customers to know about other projects or their existence. 
 
Is there a way the customer (after logging in through the web interface) can only see items related to his project/contract without knowing what or how many projects are currently being handled by the service company?.

It would be great if it is possible to change the fields under "Submit Support Ticket" such that users' view may be restricted as desired.

Best regards.

**Comment by SythilTech** [comment] 2018-09-10 03:18
Hello,

Yes the module is designed to allow any staff member with sufficient knowledge to answer a ticket, this is usefully in situations where ticket have been assign to the wrong category by the customer and saves having to be reassigned by staff.

You can however restrict what tickets a staff member can see by creating a record rule with the domain
[('category.cat_user_ids','=',user.id)]
If you a set so this applies to Website Support / Support Staff group, this will result in staff only being able to see tickets in categories they have been assigned to.

Hopefully this meets your requirements.

**Comment by hindsa-nabeel** [comment] 2018-09-10 10:34
Thanks Steven,
The above is certainly useful for internal segregation of ques, but the concern comes from the new General Data Protection Regulations (GDPR), which came into effect end of May 2018, where it is important that a data subject's (usually a person or entity) privacy is maintained, including information that can hint or lead to further classified information being inadvertently disclosed.

It is fine if the User/Customer sends a ticket to the wrong Q, the internal dispatcher will deal with that. It is very common that the customer will raise a ticket for an error appearing in a module he/she is using, to find later that it is being handled by a developer for a different module, because the cause is there. Thankfully, functionalities of moving tickets between Qs or Support Consultants (module support) or Escalation/de-Escalation to different level (such as Developers) and changing priority levels are all available in your software.

A scenario of a company that is providing Software Support or Consulting Services to customers and answering general inquiries from the public, hence:
1- Customer (Logged-in) may raise tickets and set priorities for his project/contract in a particular Q or any Q made available to him.
2- J Public (NOT Logged-in) may raise a ticket informing about a general issue or requesting information, but may not set ticket priority and usually it is set to Low.

This prompts the need for different fields appearing to Registered (logged-in) user and Public (not logged-in) user. Also changes to the fields (usually restrictions or facilitations controlled by the company offering the services) appearing for the registered users.

The ultimate responsibility for data security falls on the Data Controller in the company keeping the data and/or providing the services. But he/she needs the tools to ensure that customer privacy is built in the system and responsibly maintained.

Best regards, Nabeel.

**Comment by SythilTech** [comment] 2018-09-11 00:10
Ok, I think I have a better understanding of you requirements now.

I have introduced a new feature in version 1.3.4 that lets you limit what ticket categories will show when submitting a new ticket depending on the users group.

e.g. Only employees can submit tickets to technical support, basically this gives you max flexibility above just logged in or public user profiling.

There is also an option that lets you limit if priority can be set by public or logged in users under the setting screen.

If you have any additional requirements can you please be more specific.

**Comment by hindsa-nabeel** [comment] 2018-09-11 03:31
Thanks Steven,

Well done, I had a short review of the development and I think it may suffice. It is 4:30 am and I will have an other go at setting it up later in the morning, where I will close it or add further updates.

Best regards, Nabeel.

**Comment by hindsa-nabeel** [comment] 2018-09-11 13:02
I have configured the system and was quite happy with it, then I had one more user create himself through the web page. For some reason, the Sign-in at the top right corner has gone!! Now the page had (Home, Contact Us and Support) only, and the user (if logged-in). I went through a lot of configuration menus to see the reason for the disappearance of Sign-in, to no avail. So I decided to uninstall update Website module, then uninstall Website (which has 3 dependent modules) and reinstall it.

By the way, I tried Customize --> Settings --> Show Sign in (in main frontend layout) etc.. To no avail.

Now, Website_Support 1.3.5 fails to install and produces an error.

I know it is very silly, but I wanted to test the extent of the damage when I go this far, I am not expecting a resolution, but I thought it might point to a weak point somewhere.. I have deleted Odoo 11 and reinstalled it (no change) and dropped the database and installed a new one, now everything appears again, but I lost all my configuration. I will attempt to rebuild everything afresh.

The error when attempting to install Website_Support 1.3.5 (in case there is something significant):

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-42>", line 2, in button_immediate_install
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 449, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 380, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 274, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 153, in load_module_graph
    registry.init_models(cr, model_names, {'module': package.name})
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 306, in init_models
    model._auto_init()
  File "/opt/odoo/odoo11/odoo/models.py", line 2219, in _auto_init
    new = field.update_db(self, columns)
  File "/opt/odoo/odoo11/odoo/fields.py", line 1944, in update_db
    return super(Many2one, self).update_db(model, columns)
  File "/opt/odoo/odoo11/odoo/fields.py", line 846, in update_db
    self.update_db_notnull(model, column)
  File "/opt/odoo/odoo11/odoo/fields.py", line 886, in update_db_notnull
    model._init_column(self.name)
  File "/opt/odoo/odoo11/odoo/models.py", line 2136, in _init_column
    value = field.default(self)
  File "/opt/odoo/odoo11/custom-addons/website_support/models/website_support_ticket.py", line 48, in _default_priority_id
    default_priority = self.env['website.support.ticket.priority'].search([('sequence','=','1')])
  File "/opt/odoo/odoo11/odoo/models.py", line 1480, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/opt/odoo/odoo11/odoo/models.py", line 3792, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column website_support_ticket_priority.sequence does not exist
LINE 1: ....id FROM "website_support_ticket_priority" WHERE ("website_s...
                                                             ^

**Comment by SythilTech** [comment] 2018-09-12 00:43
Thank you for bringing this issue to my attention, I was able to reproduce the issue of a disappearing sign up menu.

I have released version 1.3.6 which will prevent any future user creations from messing up the sign in link.

You can retrospectively solve this issue by going to the Settings->Users menu then choosing Inactive Users from the filter list, once there click on the Public User and assign them to the Public group, this should result in signed out users being able to see the sign in link again.

I was not able to reproduce the install issue though, you may want to try restarting your Odoo instance as it seems to have failed to add a field which is normally only an upgrade issue but might also resolve this install issue.

**Comment by hindsa-nabeel** [comment] 2018-09-12 11:02
Thanks for the update,
I could not recover the menu because I reinstalled from afresh.
However, on another machine, I had CRM installed, so I upgraded to Website Support from 1.2.13 to 1.3.5, then removed CRM and few other modules. I then lost the Administrator's Settings Dashboard...

Here is the error if it makes sense:
P.S. I was destructive testing and I am not expecting much here as well. But I am forwarding this error in case you detect some code that needs tidying, if any is found. 

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_cron.py", line 280, in _try_lock
    [tuple(self.ids)], log_exceptions=False)
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.OperationalError: could not obtain lock on row in relation "ir_cron"


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1575, in unlink_if_refcount
    self.env[model].browse(res_id).unlink()
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_cron.py", line 294, in unlink
    self._try_lock()
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_cron.py", line 283, in _try_lock
    raise UserError(_("Record cannot be modified right now: "
odoo.exceptions.UserError: ('Record cannot be modified right now: This cron task is currently being executed and may not be modified Please try again in a few minutes', '')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo11/odoo/http.py", line 650, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo11/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo11/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo11/odoo/http.py", line 692, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo11/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 936, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo11/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 938, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/odoo11/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo11/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/module/wizard/base_module_uninstall.py", line 55, in action_uninstall
    return modules.button_immediate_uninstall()
  File "<decorator-gen-51>", line 2, in button_immediate_uninstall
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 567, in button_immediate_uninstall
    return self._button_immediate_function(type(self).button_uninstall)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 542, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/odoo/odoo11/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/odoo/odoo11/odoo/modules/loading.py", line 437, in load_modules
    Module.browse(modules_to_remove.values()).module_uninstall()
  File "<decorator-gen-50>", line 2, in module_uninstall
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 71, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/addons/base/module/module.py", line 465, in module_uninstall
    self.env['ir.model.data']._module_data_uninstall(modules_to_remove)
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1585, in _module_data_uninstall
    undeletable += unlink_if_refcount(item for item in to_unlink if item[0] not in ('ir.model', 'ir.model.fields', 'ir.model.constraint'))
  File "/opt/odoo/odoo11/odoo/addons/base/ir/ir_model.py", line 1579, in unlink_if_refcount
    self._cr.execute('ROLLBACK TO SAVEPOINT record_unlink_save')
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/opt/odoo/odoo11/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: no such savepoint

**Closed as completed** 2018-09-13 13:06 UTC
